development:
  adapter: postgresql
  database: pong_development
  pool: 5
  timeout: 5000
  template: template0

test:
  adapter: postgresql
  database: pong_test
  pool: 5
  timeout: 5000
  template: template0
